- src/client/airplanedocgenerator/.env
- src/client/airplanedocgenerator/index.js
- src/client/airplanedocgenerator/package-lock.json
- src/client/airplanedocgenerator/package.json
- src/client/airplanedocgenerator/readme-execução.md
- src/client/airplanedocgenerator/start-app.js
Adicionei dependência concurrently, wait-on e fiz possível rodar electron junto de react e sem react abrir uma nova pagina.
> Melhorado desenvolvimento com electron e react

- doc/manuais/readme-client.md
- src/client/airplanedocgenerator/.env
- src/client/airplanedocgenerator/index.js
- src/client/airplanedocgenerator/package-lock.json
- src/client/airplanedocgenerator/package.json
- src/client/airplanedocgenerator/readme-execução.md
- src/client/airplanedocgenerator/start-app.js
Criado manual de montagem de ambiente client e execução para desenvolvimento do mesmo.
> Manual client

- doc/README.md
- src/server/AirplaneManualGenerator/pom.xml
- src/server/AirplaneManualGenerator/src/main/resources/application.properties
O arquivo application.properties foi configurado para a conexão com o banco de dados
_**Excluir a branch após aceitar o PR**_
> Adicionando configurações do banco de dados

- src/client/airplanedocgenerator/src/Application.js
- src/client/airplanedocgenerator/src/index.js
- src/client/airplanedocgenerator/src/views/CreationScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
- src/client/airplanedocgenerator/tailwind.config.js
💻 🖱️ Criei a página de criação de um projeto, o mais próximo que consegui com o que explorei do Tailwind. Também deixei "responsivo" pra tudo continuar enxergável mesmo se diminuir a janela.
🤔 💭 Estive pensando que na hora que a usuário escolhe o arquivo, o texto do input deveria mudar, mas não sei como fazer isso com o React...
⚠️ Pode apagar a branch depois de aceitar a PR, acredito eu ⚠️
> Criação de um projeto

- src/client/airplanedocgenerator/src/utils/pagesUtils.js
- src/client/airplanedocgenerator/src/views/CreationScreen.js
- src/client/airplanedocgenerator/src/views/HomeScreen.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
Fiz a exportação de algumas funções que estavam repetidas.
⚠️ Pode apagar a branch depois que aceitar a PR. ⚠️
> Arquivo de utilitários

- src/client/airplanedocgenerator/src/Application.js
- src/client/airplanedocgenerator/src/assets/components/RegisterUser.js
- src/client/airplanedocgenerator/src/assets/components/SimpleInput.js
- src/client/airplanedocgenerator/src/assets/components/TopBar.js
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/filters/AuthenticationFilter.java
Através da função setRegisterUserState é possível controlar a exibição do componente de registro de usuários, essa função já é passada para o componente, dessa forma ele já é autônomo em relação a isso, basta apenas, quando o menu de funcionalidades extras for criado, chamar por essa função para fazer o componente aparecer
O componente também será finalizado no momento da criação do serviço de registro de usuários no servidor
**_Excluir a branch após aceitar o PR_**
> Componente de cadastro de novos usuários

- src/client/airplanedocgenerator/src/Application.js
- src/client/airplanedocgenerator/src/assets/components/RegisterUser.js
- src/client/airplanedocgenerator/src/assets/components/SimpleInput.js
- src/client/airplanedocgenerator/src/assets/components/TopBar.js
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/AirplaneManualGeneratorApplication.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/AuthenticationController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/requestsBody/LoginCredentials.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/converters/PasswordConverter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/filters/AuthenticationFilter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/Administrador.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/Usuario.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/UsuarioPadrao.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/AdministradorRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/UsuarioRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/Password.java
- src/server/AirplaneManualGenerator/src/main/resources/application.properties
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/controllers/AuthenticationControllerTest.java
Todo o fluxo de autenticação do usuário foi criado
Os testes unitários também foram criados para o controller
Para testar, basta rodar como jUnit test a classe AuthenticationControllerTest, se tudo ficar verde, sucesso 🙂
**_Apagar branch após aceitar_**
> Autenticação do usuário

- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/AirplaneManualGeneratorApplication.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/AuthenticationController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/UsuarioController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/requestsBody/LoginCredentials.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/requestsBody/RegisterUser.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/converters/PasswordConverter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/filters/AuthenticationFilter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/Administrador.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/Usuario.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/UsuarioPadrao.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/factories/UsuarioFactory.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/AdministradorRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/UsuarioRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/Password.java
- src/server/AirplaneManualGenerator/src/main/resources/application.properties
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/controllers/AuthenticationControllerTest.java
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/controllers/UsuarioControllerTest.java
_**Revisar primeiro o PR: https://github.com/Syank/AirplaneDocGenerator/pull/19**_
O endpoint do servidor e todo seu sistema de cadastro de novos usuários foi finalizado
Os testes para testar o sistema deste PR já foram feitos, para verificar, basta executar a classe de testes UsuarioControllerTest
_**Apagar a branch após aceitar o PR**_
> Cadastro de novos usuários

- src/client/airplanedocgenerator/src/utils/ServerRequester.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/AirplaneManualGeneratorApplication.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/filters/CORSFilter.java
Agora para entrar no sistema, o usuário deverá se autenticar, o servidor, sempre que for inicializado, garantirá que existira um usuário administrador padrão
Para testar, execute e aplicação e faça login com a conta do usuário administrador padrão
_**Apagar a branch após aceitar o PR**_
> Habilitando verificação de login

- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/AirplaneManualGeneratorApplication.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/requestsBody/NewProject.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/Projeto.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/ProjetoRepository.java
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/controllers/ProjetoControllerTest.java
Serviços e testes para as seguintes funcionalidades foram feitos:
- Listagem de todos os projetos
- Criação de um projeto
> Criação e listagem de projetos

- src/client/airplanedocgenerator/package.json
- src/client/airplanedocgenerator/src/assets/components/Notifications.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
Agora quando o usuário cria algo, exclui etc. podemos exibir uma notificação envolvendo o status do que foi feito.
⬇️   **Adicionei uma dependência** ⬇️ 
- Criei as funções que exibem as notificações de acordo com o necessário;
- Substituí onde vi que tinha console.log ou um alert simples (se algum lugar tiver passado, é só solicitar mudanças).
⚠️ Pode apagar a branch após aceitar, acredito eu ⚠️
> Adicionando notificações

- src/client/airplanedocgenerator/package.json
- src/client/airplanedocgenerator/src/assets/components/Notifications.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
- Ao selecionar um arquivo, agora o input levará o nome do arquivo selecionado;
- Adicionei, também, um "limitador" no formato de arquivos que o usuário pode selecionar. Por enquanto há somente .xls e .xlsx.
⚠️ Verificar, primeiramente, a PR #24 ⚠️ 
🗑️ Acredito que possa apagar a branch após aceitar as alterações
> Melhoria: mudança no input do arquivo na newProjectScreen

- src/client/airplanedocgenerator/package-lock.json
- src/client/airplanedocgenerator/src/assets/components/Tooltip.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
Só o input mask que não consegui criar ainda porque envolve coisas que se tudo der certo vou aprender com aquela minha outra tarefa que ta blocked. Só usar pattern não da porque react não usa html5.
> criado tooltip

- src/client/airplanedocgenerator/src/assets/components/Notifications.js
- src/client/airplanedocgenerator/src/assets/components/Tooltip.js
- src/client/airplanedocgenerator/src/views/CreationScreen.js
- src/client/airplanedocgenerator/src/views/HomeScreen.js
- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
- Adicionei um link que disponibiliza todos os ícones do sweet alert;
- Corrigi de class para className no componente do tooltip;
- Melhorei a descrição do tooltip;
- Adicionei notificações nas funcionalidades não finalizadas;
- Corrigi problema no login. Ao inserir os dados corretamente, logava, mas exibia uma mensagem de erro.
⚠️ Pode apagar a branch depois que aceitar ⚠️ 
💭 Sugestões: só pedir a alteração
> Correções + adição das notificações em funcionalidades não finalizadas

- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Codelist.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Linha.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Projeto.java
Por favor, testar para ver se eu não inverti nada. Pelo que conferi, não. Segui os relacionamentos da nova versão do modelo conceitual.
⚠️ Apagar a branch depois de aceitar.
> Relacionamentos entre projetos, codelists, linhas e remarks

- src/client/airplanedocgenerator/src/assets/components/Tooltip.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
Consertado bug em que quando texto era muito longo de outra tooltip imposibilitava o primeiro de ativar evento de hover.
> Consertado Novo Bug

- doc/README.md
- src/server/AirplaneManualGenerator/pom.xml
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/AirplaneManualGeneratorApplication.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/config/SpringFoxConfig.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/requestsBody/NewProject.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/filters/AuthenticationFilter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Codelist.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Linha.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Projeto.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Remark.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/builders/CodelistBuilder.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/builders/ProjetoBuilder.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/builders/RemarkBuilder.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/enumarations/CodelistColumn.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/FileUtils.java
- src/server/AirplaneManualGenerator/src/main/resources/application.properties
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/controllers/ProjetoControllerTest.java
- src/server/AirplaneManualGenerator/src/test/java/api/crabteam/entities/CodelistTest.java
O endpoint /project/create agora pode receber uma codelist para vincular ao projeto sendo criado
> Atualizando endpoint para criação de projetos

- src/client/airplanedocgenerator/src/views/LoginScreen.js
- src/client/airplanedocgenerator/src/views/NewProjectScreen.js
Adicionado, na tela de login, mensagem para falha na conexão com o servidor.
> Mensagem de erro servidor

- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
adicionando endpoint do método PUT
> método PUT

- src/client/airplanedocgenerator/index.js
- src/client/airplanedocgenerator/src/assets/components/TopBar.js
- src/client/airplanedocgenerator/src/preload.js
- src/server/AirplaneManualGenerator/src/main/resources/application.properties
Co-Authored-By: Rafael Furtado <49576121+Syank@users.noreply.github.com>
> unmaximize

- src/client/airplanedocgenerator/src/assets/components/CodelistManager.js
- src/client/airplanedocgenerator/src/assets/components/Notifications.js
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/CodelistController.java
1. Os arquivos das linhas antigas são apagados;
2. É exibida uma caixa de confirmação para o usuário, para que ele tenha certeza de que realmente deseja fazer a ação;
3. Caminho para salvar a nova codelist foi alterado e agora está salvando dentro da pasta do projeto de manual.
📱 Qualquer bug é só chamar!!
⚠️ Pode apagar a branch após aceitar a PR ⚠️
> Verificação da funcionalidade de importar uma nova codelist

- src/client/airplanedocgenerator/index.js
- src/client/airplanedocgenerator/src/assets/components/CodelistManager.js
- src/client/airplanedocgenerator/src/preload.js
- src/server/AirplaneManualGenerator/pom.xml
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/CodelistController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/builders/CodelistBuilder.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/enumarations/CodelistColumn.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/CodelistExporter.java
Agora o usuário pode exportar a codelist de um projeto. É feito o download de um arquivo do Excel, que pode ser importado no sistema novamente.
⚠️ Pode apagar a branch após aceitar a PR ⚠️ 
📱 Qualquer bug é só chamar!!
💀 Não se esqueça de testar 💀
> Exportação de uma codelist

- src/client/airplanedocgenerator/index.js
- src/client/airplanedocgenerator/src/assets/components/CodelistManager.js
- src/client/airplanedocgenerator/src/preload.js
- src/client/airplanedocgenerator/src/views/ProjectAdministrationScreen.js
- src/server/AirplaneManualGenerator/pom.xml
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/CodelistExporter.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/FileVerifications.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/ProjectExporter.java
Agora o usuário pode exportar o projeto em um arquivo zip. As pastas que estão vazias também são inclusas no arquivo zipado.
⚠️ Ao aceitar a PR, pode apagar a branch ⚠️ 
📱 Qualquer bugzinho é só chamar!!
💀 É melhor testar 💀
> Exportação do projeto

- src/client/airplanedocgenerator/src/views/SelectProjectScreen.js
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/controllers/ProjetoController.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/entities/Projeto.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/CodelistRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/model/repositories/ProjetoRepository.java
- src/server/AirplaneManualGenerator/src/main/java/api/crabteam/utils/FileVerifications.java
1. As linhas são apagadas do banco de dados;
2. A codelist é apagada do banco de dados;
3. A pasta no "servidor" também é apagada;
4. A lista (para o usuário) é atualizada após a exclusão do projeto
💀 Por favor, **teste** a funcionalidade 💀 
📱 Qualquer bug é só chamar!!
⚠️ Ao aceitar a PR, pode apagar a branch ⚠️
> Exclusão de projetos

- src/client/airplanedocgenerator/src/Application.js
Adicionado página importProjectScreen ao previousPageMap para habilitar funcionalidade de voltar uma página.
> Corrigido botão "voltar" da página de importar um projeto
